use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

include!("app_commands.rs");

const APP_ICON_SVG: &[u8] = include_bytes!("../src/mewrk-icon.svg");
const APP_ICON_SMALL_SVG: &[u8] = include_bytes!("../src/mewrk-icon-small.svg");
const APP_ICON_SIZES: [u32; 6] = [16, 24, 32, 48, 128, 256];
/// The smallest frame the full icon — prompt chevron and mark — is drawn at.
///
/// `mewrk-icon.svg` puts a `›` prompt before the mark, and below a 32px frame
/// the chevron's stroke is thinner than a pixel and blurs into the plate. The
/// 16 and 24 frames therefore come from `mewrk-icon-small.svg`, which is the
/// mark alone on the same plate, drawn larger. Both are inputs to this build
/// script, so both have to be registered in `browserDevRustFingerprintEntries`
/// and in the Pages workflow's path filter.
const APP_ICON_FULL_MIN_SIZE: u32 = 32;
/// The bare mark, black on clear: the source of the macOS menu bar icon. An
/// input to this build script like the two icons, so registered beside them in
/// `browserDevRustFingerprintEntries`.
const BRAND_MARK_SVG: &[u8] = include_bytes!("../src/mewrk-mark.svg");
/// `tray-icon` draws a status item's image 18pt tall whatever its pixels, so
/// the menu bar icon is that height at 2x, with the mark 15pt of it: 30px keeps
/// the mark's 3:5 width a whole 18px, and the 1.5pt above and below sits it at
/// the weight of the system's own menu bar glyphs.
const TRAY_TEMPLATE_HEIGHT: u32 = 36;
const TRAY_TEMPLATE_MARK_HEIGHT: u32 = 30;

macro_rules! app_command_names {
    ($($command:ident),* $(,)?) => {
        &[$(stringify!($command)),*]
    };
}

const APP_COMMANDS: &[&str] = mewrk_app_commands!(app_command_names);

fn main() {
    // macOS only: the Chromium Embedded Framework distribution cef-dll-sys fetched and compiled
    // this build against. A development run loads the built-in browser's engine from there;
    // a bundle carries its own copy in Contents/Frameworks (see src/cef_host).
    if let Ok(directory) = env::var("DEP_CEF_DLL_WRAPPER_CEF_DIR") {
        println!("cargo:rustc-env=MEWRK_CEF_DIR={directory}");
    }
    prefer_mingw_toolchain();
    export_build_facts();
    ensure_bundled_agents_dir();
    println!("cargo:rerun-if-changed=../src/mewrk-icon.svg");
    println!("cargo:rerun-if-changed=../src/mewrk-icon-small.svg");
    println!("cargo:rerun-if-changed=../src/mewrk-mark.svg");
    // `generate_context!` embeds Info.plist (its privacy usage strings) into the macOS
    // binary, but the macro does not tell Cargo, so an edit would not reach a dev build.
    println!("cargo:rerun-if-changed=Info.plist");
    let output_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let icon_path = output_dir.join("mewrk-icon.ico");
    let icon = generated_icon();
    fs::write(&icon_path, &icon).expect("write generated Windows icon");
    let manifest_icon =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"))
            .join("icons")
            .join("icon.ico");
    fs::create_dir_all(manifest_icon.parent().expect("icon parent"))
        .expect("create generated icon directory");
    if !matches!(fs::read(&manifest_icon), Ok(existing) if existing == icon) {
        fs::write(&manifest_icon, &icon).expect("write generated application icon");
    }
    stage_non_windows_icons(manifest_icon.parent().expect("icon parent"));
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        write_if_changed(&output_dir.join("tray-template.png"), &render_tray_template_png());
    }

    let windows = if embed_windows_manifest_for_all_link_targets(&output_dir) {
        // The Windows manifest is already linked into every executable (bins and every
        // cargo test harness) above. tauri-build only covers bins, and adding its copy on
        // top would link a second RT_MANIFEST resource into them.
        tauri_build::WindowsAttributes::new_without_app_manifest()
    } else {
        // Keep the same explicit asInvoker/uiAccess=false boundary on MSVC and
        // any future Windows linker path instead of relying on tauri-build's
        // implicit default manifest.
        tauri_build::WindowsAttributes::new().app_manifest(include_str!("windows-app-manifest.xml"))
    }
    .window_icon_path(icon_path);
    let attributes = tauri_build::Attributes::new()
        .windows_attributes(windows)
        .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
    tauri_build::try_build(attributes).expect("build Tauri application metadata");
    prune_retired_command_permissions();
}

/// Deletes the generated permission files of commands that no longer exist.
///
/// `tauri_build::try_build` writes one `permissions/autogenerated/<command>.toml` per entry
/// of `APP_COMMANDS`, but it only ever *adds*: retiring a command leaves its file behind
/// forever. The directory is gitignored build output, so the residue is invisible to review
/// and survives every rebuild — the ACL then advertises `allow-<retired-command>` identifiers
/// that no command and no capability back.
///
/// Only files this build script's own generator could have written are considered: a
/// `<stem>.toml` directly in the directory, carrying tauri-build's header, whose stem is not
/// a live command. Anything else is left alone.
fn prune_retired_command_permissions() {
    let directory = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"))
        .join("permissions")
        .join("autogenerated");
    let Ok(entries) = fs::read_dir(&directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("toml") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        if APP_COMMANDS.contains(&stem) {
            continue;
        }
        // A hand-written permission file that happens to sit here is not this script's to
        // delete; the header is what marks the file as generated.
        if !matches!(fs::read_to_string(&path), Ok(text) if text.starts_with("# Automatically generated"))
        {
            continue;
        }
        if fs::remove_file(&path).is_ok() {
            println!("cargo:warning=删除已退役命令的权限文件 {stem}.toml");
        }
    }
}

/// Makes sure the bundled agent resource directory exists.
///
/// `tauri.conf.json` bundles `bundled-agents/` (as `remote-agents/` in the
/// app's resources), and a resource path that does not exist fails every build —
/// `cargo check` included. It holds only the agent for the platform being built,
/// which this computer runs its own sandboxed commands through; builds for every
/// other machine are fetched when a machine first needs one
/// (`src/components/remote_agents.rs`). `npm run build:remote-agents -- --bundle`
/// fills it; an empty directory only means the local agent is fetched too.
fn ensure_bundled_agents_dir() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let directory = manifest.join("bundled-agents");
    fs::create_dir_all(&directory).expect("create the bundled agent resource directory");
    println!("cargo:rerun-if-changed={}", directory.display());
}

/// Facts about this build the crate reads with `env!`.
///
/// - `MEWRK_TARGET_TRIPLE`: Cargo's `TARGET`, the one authoritative value — the
///   remote agent catalog and the component channels name builds by it, and
///   parsing `rustc -vV` a second time elsewhere would only make a second thing
///   that can drift.
/// - `MEWRK_CLAUDE_AGENT_SDK_VERSION`: the `@anthropic-ai/claude-agent-sdk`
///   version `aisdk-service` is written and checked against. Neither the SDK nor
///   the Claude Code it drives ships with Mewrk any more — both are installed
///   from npm on the provider page (`src/components/claude_agent.rs`) — so this
///   is the floor of what this host offers to install, not a file it carries.
fn export_build_facts() {
    let target = env::var("TARGET").expect("TARGET is set by Cargo for build scripts");
    println!("cargo:rustc-env=MEWRK_TARGET_TRIPLE={target}");

    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let package = manifest
        .parent()
        .expect("repository root")
        .join("aisdk-service")
        .join("package.json");
    println!("cargo:rerun-if-changed={}", package.display());
    let text = fs::read_to_string(&package)
        .unwrap_or_else(|error| panic!("读不到 {}：{error}", package.display()));
    let version = json_string_field(&text, "@anthropic-ai/claude-agent-sdk")
        .unwrap_or_else(|| panic!("{} 没有声明 @anthropic-ai/claude-agent-sdk", package.display()));
    assert!(
        !version.is_empty() && version.chars().all(|c| c.is_ascii_digit() || c == '.'),
        "{} 里的 @anthropic-ai/claude-agent-sdk 必须钉成精确版本（如 0.3.284），现在是 {version}",
        package.display(),
    );
    println!("cargo:rustc-env=MEWRK_CLAUDE_AGENT_SDK_VERSION={version}");
}

/// Reads one string field out of a package manifest.
///
/// A whole JSON parser is not a build dependency here, and the input is the
/// repository's own `package.json` rather than user input: the field is found by
/// key and the answer is the next quoted string.
fn json_string_field(text: &str, key: &str) -> Option<String> {
    let after_key = text.split_once(&format!("\"{key}\""))?.1;
    let after_colon = after_key.split_once(':')?.1;
    let opened = after_colon.split_once('"')?.1;
    Some(opened.split_once('"')?.0.to_owned())
}

///
/// tauri-build (via tauri-winres/embed-resource) attaches the manifest with
/// `cargo:rustc-link-arg-bins`, which cargo test harnesses never receive. Without a manifest
/// declaring the Common-Controls v6 dependency, the loader resolves comctl32.dll to the legacy
/// v5 copy in System32, which lacks `TaskDialogIndirect` (imported through muda/rfd), and MSVC
/// test executables die at load with STATUS_ENTRYPOINT_NOT_FOUND. Linking the explicit manifest
/// everywhere also makes GNU ld drop MinGW's default manifest object, leaving each executable
/// with exactly one RT_MANIFEST.
fn embed_windows_manifest_for_all_link_targets(output_dir: &Path) -> bool {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return false;
    }
    let manifest_path = output_dir.join("mewrk-app.manifest");
    fs::write(&manifest_path, include_str!("windows-app-manifest.xml"))
        .expect("write Windows application manifest");
    let resource_path = output_dir.join("mewrk-manifest.rc");
    let resource_manifest_path = manifest_path.to_string_lossy().replace('\\', "/");
    fs::write(
        &resource_path,
        format!("1 24 \"{resource_manifest_path}\"\n"),
    )
    .expect("write Windows manifest resource script");

    match env::var("CARGO_CFG_TARGET_ENV").as_deref() {
        Ok("gnu") => {
            let object_name = "mewrk-manifest.o";
            let windres = ["windres", "x86_64-w64-mingw32-windres"]
                .into_iter()
                .find(|name| {
                    Command::new(name)
                        .arg("--version")
                        .output()
                        .is_ok_and(|output| output.status.success())
                })
                .expect("windres is required to embed the Windows manifest on windows-gnu");
            let status = Command::new(windres)
                .current_dir(output_dir)
                .args(["-O", "coff", "-i", "mewrk-manifest.rc", "-o", object_name])
                .status()
                .expect("run windres");
            assert!(status.success(), "windres failed with {status}");
            println!(
                "cargo:rustc-link-arg={}",
                output_dir.join(object_name).display()
            );
            true
        }
        Ok("msvc") => {
            embed_resource::compile_for_everything(&resource_path, embed_resource::NONE)
                .manifest_required()
                .expect("compile Windows application manifest for all MSVC targets");
            true
        }
        _ => false,
    }
}

fn prefer_mingw_toolchain() {
    #[cfg(all(windows, target_env = "gnu"))]
    {
        let Some(path) = env::var_os("PATH") else {
            return;
        };
        let entries = env::split_paths(&path).collect::<Vec<_>>();
        let Some(mingw_bin) = entries
            .iter()
            .find(|entry| {
                entry
                    .components()
                    .rev()
                    .take(2)
                    .map(|part| part.as_os_str().to_string_lossy().to_lowercase())
                    .collect::<Vec<_>>()
                    == ["bin", "mingw64"]
            })
            .cloned()
        else {
            return;
        };
        let reordered = std::iter::once(mingw_bin.clone())
            .chain(entries.into_iter().filter(|entry| entry != &mingw_bin))
            .collect::<Vec<_>>();
        if let Ok(path) = env::join_paths(reordered) {
            env::set_var("PATH", path);
        }
    }
}

/// Renders the icon as a PNG `size` pixels square, from the full icon or, below
/// [`APP_ICON_FULL_MIN_SIZE`], from the mark alone.
fn render_icon_png(size: u32) -> Vec<u8> {
    render_icon_pixmap(size)
        .encode_png()
        .expect("encode Mewrk icon PNG")
}

fn render_icon_pixmap(size: u32) -> resvg::tiny_skia::Pixmap {
    let options = resvg::usvg::Options::default();
    let (svg, what) = if size >= APP_ICON_FULL_MIN_SIZE {
        (APP_ICON_SVG, "the canonical Mewrk SVG icon")
    } else {
        (APP_ICON_SMALL_SVG, "the small-frame Mewrk SVG icon")
    };
    let tree =
        resvg::usvg::Tree::from_data(svg, &options).unwrap_or_else(|_| panic!("parse {what}"));
    let mut pixmap =
        resvg::tiny_skia::Pixmap::new(size, size).expect("allocate Mewrk icon pixmap");
    let transform = resvg::tiny_skia::Transform::from_scale(
        size as f32 / tree.size().width(),
        size as f32 / tree.size().height(),
    );
    resvg::render(&tree, transform, &mut pixmap.as_mut());
    pixmap
}

/// Renders the macOS menu bar icon: the mark alone, centred on a clear canvas
/// as wide as the mark. It is a template image — only its alpha counts, and the
/// menu bar paints it in whatever colour suits a light, dark or highlighted
/// bar — so the app icon's coloured plate has no place in it.
fn render_tray_template_png() -> Vec<u8> {
    let options = resvg::usvg::Options::default();
    let tree = resvg::usvg::Tree::from_data(BRAND_MARK_SVG, &options)
        .unwrap_or_else(|_| panic!("parse the Mewrk brand mark SVG"));
    let scale = TRAY_TEMPLATE_MARK_HEIGHT as f32 / tree.size().height();
    let width = (tree.size().width() * scale).round() as u32;
    let mut pixmap = resvg::tiny_skia::Pixmap::new(width, TRAY_TEMPLATE_HEIGHT)
        .expect("allocate the menu bar icon pixmap");
    let top = (TRAY_TEMPLATE_HEIGHT - TRAY_TEMPLATE_MARK_HEIGHT) as f32 / 2.0;
    let transform = resvg::tiny_skia::Transform::from_scale(scale, scale).post_translate(0.0, top);
    resvg::render(&tree, transform, &mut pixmap.as_mut());
    pixmap.encode_png().expect("encode the menu bar icon PNG")
}

/// Writes `bytes` to `path` unless it already holds exactly them, so an
/// unchanged icon does not touch the file and retrigger downstream work.
fn write_if_changed(path: &Path, bytes: &[u8]) {
    if !matches!(fs::read(path), Ok(existing) if existing == bytes) {
        fs::write(path, bytes).unwrap_or_else(|error| panic!("write {}: {error}", path.display()));
    }
}

/// The icons a non-Windows target needs, rendered from the same two SVGs as
/// `icon.ico`, so a fresh clone builds without a manual icon step.
///
/// `tauri::generate_context!` opens `icons/icon.png` for the window icon on
/// every target but Windows, and the macOS bundler takes the app icon from
/// `icons/icon.icns` (`tauri.macos.conf.json`). Both are build output, ignored
/// by Git; only `icon.ico`, the shipped Windows icon, is tracked.
fn stage_non_windows_icons(icons: &Path) {
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "windows" {
        return;
    }
    write_if_changed(&icons.join("icon.png"), &render_icon_png(512));
    if target_os == "macos" {
        write_if_changed(&icons.join("icon.icns"), &generated_icns());
    }
}

/// An `.icns` holding one image per slot macOS looks for, standard and Retina,
/// in the element types `iconutil` writes.
///
/// The format is a big-endian `icns` header and length, then one
/// `type, length, data` element per image. The two 1x slots below 64px, `ic04`
/// and `ic05`, take [`icns_argb`] data; every other type takes PNG. Don't put
/// PNGs in `icp4`/`icp5` instead: macOS does not decode those as PNG, and
/// Finder's 16pt list rows and 32pt icons showed the bytes as coloured noise.
fn generated_icns() -> Vec<u8> {
    const ELEMENTS: [(&[u8; 4], u32); 10] = [
        (b"ic04", 16),
        (b"ic05", 32),
        (b"ic11", 32),
        (b"ic12", 64),
        (b"ic07", 128),
        (b"ic13", 256),
        (b"ic08", 256),
        (b"ic14", 512),
        (b"ic09", 512),
        (b"ic10", 1024),
    ];
    let mut rendered = std::collections::BTreeMap::new();
    let mut body = Vec::new();
    for (kind, size) in ELEMENTS {
        let pixmap = rendered
            .entry(size)
            .or_insert_with(|| render_icon_pixmap(size));
        let data = match kind {
            b"ic04" | b"ic05" => icns_argb(pixmap),
            _ => pixmap.encode_png().expect("encode Mewrk icon PNG"),
        };
        body.extend_from_slice(kind);
        body.extend_from_slice(&(8 + data.len() as u32).to_be_bytes());
        body.extend_from_slice(&data);
    }
    let mut icns = Vec::with_capacity(8 + body.len());
    icns.extend_from_slice(b"icns");
    icns.extend_from_slice(&(8 + body.len() as u32).to_be_bytes());
    icns.extend_from_slice(&body);
    icns
}

/// An `ic04`/`ic05` payload: `ARGB`, then the alpha, red, green and blue
/// planes, unpremultiplied, each packed on its own with the icns run-length
/// code — a header byte below 0x80 copies the next `header + 1` bytes, one from
/// 0x80 up repeats the next byte `header - 125` times.
fn icns_argb(pixmap: &resvg::tiny_skia::Pixmap) -> Vec<u8> {
    let pixels = pixmap
        .pixels()
        .iter()
        .map(|pixel| pixel.demultiply())
        .collect::<Vec<_>>();
    let channels: [fn(&resvg::tiny_skia::ColorU8) -> u8; 4] = [
        |pixel| pixel.alpha(),
        |pixel| pixel.red(),
        |pixel| pixel.green(),
        |pixel| pixel.blue(),
    ];
    let mut data = b"ARGB".to_vec();
    for channel in channels {
        let plane = pixels.iter().map(channel).collect::<Vec<_>>();
        let mut at = 0;
        while at < plane.len() {
            let run = plane[at..]
                .iter()
                .take(130)
                .take_while(|&&byte| byte == plane[at])
                .count();
            if run >= 3 {
                data.extend_from_slice(&[(run + 125) as u8, plane[at]]);
                at += run;
                continue;
            }
            let start = at;
            while at < plane.len()
                && at - start < 128
                && !plane[at..].starts_with(&[plane[at]; 3])
            {
                at += 1;
            }
            data.push((at - start - 1) as u8);
            data.extend_from_slice(&plane[start..at]);
        }
    }
    data
}

fn generated_icon() -> Vec<u8> {
    let png_images = APP_ICON_SIZES
        .into_iter()
        .map(render_icon_png)
        .collect::<Vec<_>>();

    let directory_bytes = 6 + png_images.len() * 16;
    let image_bytes = png_images.iter().map(Vec::len).sum::<usize>();
    let mut icon = Vec::with_capacity(directory_bytes + image_bytes);
    icon.extend_from_slice(&0_u16.to_le_bytes());
    icon.extend_from_slice(&1_u16.to_le_bytes());
    icon.extend_from_slice(&(png_images.len() as u16).to_le_bytes());

    let mut image_offset = directory_bytes as u32;
    for (size, png) in APP_ICON_SIZES.into_iter().zip(&png_images) {
        let directory_size = if size == 256 { 0 } else { size as u8 };
        icon.extend_from_slice(&[directory_size, directory_size, 0, 0]);
        icon.extend_from_slice(&1_u16.to_le_bytes());
        icon.extend_from_slice(&32_u16.to_le_bytes());
        icon.extend_from_slice(&(png.len() as u32).to_le_bytes());
        icon.extend_from_slice(&image_offset.to_le_bytes());
        image_offset += png.len() as u32;
    }
    for png in png_images {
        icon.extend_from_slice(&png);
    }
    icon
}
