import { describe, expect, it } from "vitest";
// Vite's ?raw import loads the authoritative Rust list and the capability file as plain
// text, so this suite reasons about the committed sources without compiling anything.
import appCommandsSource from "../src-tauri/app_commands.rs?raw";
import capabilitySource from "../src-tauri/capabilities/default.json?raw";

// The file-description tool line was retired. `app_commands.rs` is the single authoritative
// list — the invoke handler and the generated ACL both come from it — so a retired command
// must be absent from it, absent from the capability allow list, and must not leave a
// generated permission file behind. The last one is build output rather than a committed
// file, which is exactly why it went unnoticed: nothing reviewed it and nothing pruned it.
const retiredCommands = [
  "tool_description_file_read",
  "tool_description_file_save",
  "tool_description_file_delete"
];

// A live command, so a parser that silently produced an empty set cannot pass this suite.
const liveCommand = "browser_close";

const permissionsDirectory = "../src-tauri/permissions/autogenerated";

// Enumerated at transform time rather than through `node:fs`, which `tsconfig.json` (no node
// types, `include: ["src"]`) does not allow in this directory. Only the keys are read; the
// loaders are never called.
const generatedPermissionFiles = Object.keys(
  import.meta.glob("../src-tauri/permissions/autogenerated/*.toml", {
    query: "?raw",
    import: "default"
  })
).map((file) => file.slice(file.lastIndexOf("/") + 1, -".toml".length));

function authoritativeCommands(): string[] {
  const callbackBody = appCommandsSource.slice(appCommandsSource.indexOf("$callback!("));
  return [...callbackBody.matchAll(/^\s+([a-z][a-z0-9_]*),\s*$/gmu)].map(([, name]) => name);
}

function grantedCommands(): string[] {
  const capability = JSON.parse(capabilitySource) as { permissions: unknown[] };
  return capability.permissions
    .filter(
      (permission): permission is string =>
        typeof permission === "string" && permission.startsWith("allow-")
    )
    .map((permission) => permission.slice("allow-".length).replaceAll("-", "_"));
}

describe("retired file-description commands", () => {
  it("parses both sources into a non-empty, agreeing command set", () => {
    const commands = authoritativeCommands();
    const granted = grantedCommands();
    // Without these two the absence assertions below would pass on an empty set.
    expect(commands.length).toBeGreaterThan(50);
    expect(commands).toContain(liveCommand);
    expect(granted).toContain(liveCommand);
    expect(new Set(granted)).toEqual(new Set(commands));
  });

  it.each(retiredCommands)("%s is registered nowhere", (command) => {
    expect(authoritativeCommands()).not.toContain(command);
    expect(grantedCommands()).not.toContain(command);
    // The kebab spelling is what the capability file and the permission identifiers use.
    expect(capabilitySource).not.toContain(`allow-${command.replaceAll("_", "-")}`);
  });

  it("leaves no generated permission file for a command that no longer exists", () => {
    // Gitignored build output: a fresh clone has not built yet, and an empty directory is
    // not drift. Once it exists, `build.rs` has just pruned it, so every file in it must
    // correspond to a live command — the retired three included.
    if (generatedPermissionFiles.length === 0) return;
    expect(
      generatedPermissionFiles,
      `${permissionsDirectory} 已生成但缺少存活命令的权限文件，说明枚举没读到真实目录`
    ).toContain(liveCommand);
    const commands = new Set(authoritativeCommands());
    const orphans = generatedPermissionFiles.filter((command) => !commands.has(command));
    expect(orphans, "重建一次即可清除（build.rs 会剪除退役命令的权限文件）").toEqual([]);
  });
});
